package br.com.gaiatosfc.model;
// Generated 22/04/2016 14:13:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adversarios generated by hbm2java
 */
@Entity
@Table(name="adversarios"
    ,schema="public"
)
public class Adversarios  implements java.io.Serializable {


     private int codAdv;
     private JogadoresAdv jogadoresAdv;
     private String nome;
     private String escudoAdv;
     private Set jogoses = new HashSet(0);

    public Adversarios() {
    }

	
    public Adversarios(int codAdv) {
        this.codAdv = codAdv;
    }
    public Adversarios(int codAdv, JogadoresAdv jogadoresAdv, String nome, String escudoAdv, Set jogoses) {
       this.codAdv = codAdv;
       this.jogadoresAdv = jogadoresAdv;
       this.nome = nome;
       this.escudoAdv = escudoAdv;
       this.jogoses = jogoses;
    }
   
     @Id 

    
    @Column(name="cod_adv", unique=true, nullable=false)
    public int getCodAdv() {
        return this.codAdv;
    }
    
    public void setCodAdv(int codAdv) {
        this.codAdv = codAdv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_jogadores_adv")
    public JogadoresAdv getJogadoresAdv() {
        return this.jogadoresAdv;
    }
    
    public void setJogadoresAdv(JogadoresAdv jogadoresAdv) {
        this.jogadoresAdv = jogadoresAdv;
    }

    
    @Column(name="nome", length=80)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="escudo_adv")
    public String getEscudoAdv() {
        return this.escudoAdv;
    }
    
    public void setEscudoAdv(String escudoAdv) {
        this.escudoAdv = escudoAdv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="adversarios")
    public Set getJogoses() {
        return this.jogoses;
    }
    
    public void setJogoses(Set jogoses) {
        this.jogoses = jogoses;
    }




}


