package br.com.gaiatosfc.model;
// Generated 22/04/2016 14:13:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jogadores generated by hbm2java
 */
@Entity
@Table(name="jogadores"
    ,schema="public"
)
public class Jogadores  implements java.io.Serializable {


     private int codJd;
     private String nomeJd;
     private String foto;
     private String posicao;
     private Integer jogosDisputados;
     private Integer gols;
     private Date dataNasc;
     private Set golses = new HashSet(0);

    public Jogadores() {
    }

	
    public Jogadores(int codJd, String nomeJd) {
        this.codJd = codJd;
        this.nomeJd = nomeJd;
    }
    public Jogadores(int codJd, String nomeJd, String foto, String posicao, Integer jogosDisputados, Integer gols, Date dataNasc, Set golses) {
       this.codJd = codJd;
       this.nomeJd = nomeJd;
       this.foto = foto;
       this.posicao = posicao;
       this.jogosDisputados = jogosDisputados;
       this.gols = gols;
       this.dataNasc = dataNasc;
       this.golses = golses;
    }
   
     @Id 

    
    @Column(name="cod_jd", unique=true, nullable=false)
    public int getCodJd() {
        return this.codJd;
    }
    
    public void setCodJd(int codJd) {
        this.codJd = codJd;
    }

    
    @Column(name="nome_jd", nullable=false, length=40)
    public String getNomeJd() {
        return this.nomeJd;
    }
    
    public void setNomeJd(String nomeJd) {
        this.nomeJd = nomeJd;
    }

    
    @Column(name="foto")
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    
    @Column(name="posicao", length=30)
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }

    
    @Column(name="jogos_disputados")
    public Integer getJogosDisputados() {
        return this.jogosDisputados;
    }
    
    public void setJogosDisputados(Integer jogosDisputados) {
        this.jogosDisputados = jogosDisputados;
    }

    
    @Column(name="gols")
    public Integer getGols() {
        return this.gols;
    }
    
    public void setGols(Integer gols) {
        this.gols = gols;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nasc", length=13)
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jogadores")
    public Set getGolses() {
        return this.golses;
    }
    
    public void setGolses(Set golses) {
        this.golses = golses;
    }




}


