package br.com.gaiatosfc.model;
// Generated 22/04/2016 14:13:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jogos generated by hbm2java
 */
@Entity
@Table(name="jogos"
    ,schema="public"
)
public class Jogos  implements java.io.Serializable {


     private int codJg;
     private Adversarios adversarios;
     private Campeonatos campeonatos;
     private Date data;
     private Integer golsPro;
     private Integer golsAdv;
     private String localJg;
     private String conteudo;
     private Integer codComentario;
     private Set golsAdvs = new HashSet(0);
     private Set golses = new HashSet(0);

    public Jogos() {
    }

	
    public Jogos(int codJg, String localJg) {
        this.codJg = codJg;
        this.localJg = localJg;
    }
    public Jogos(int codJg, Adversarios adversarios, Campeonatos campeonatos, Date data, Integer golsPro, Integer golsAdv, String localJg, String conteudo, Integer codComentario, Set golsAdvs, Set golses) {
       this.codJg = codJg;
       this.adversarios = adversarios;
       this.campeonatos = campeonatos;
       this.data = data;
       this.golsPro = golsPro;
       this.golsAdv = golsAdv;
       this.localJg = localJg;
       this.conteudo = conteudo;
       this.codComentario = codComentario;
       this.golsAdvs = golsAdvs;
       this.golses = golses;
    }
   
     @Id 

    
    @Column(name="cod_jg", unique=true, nullable=false)
    public int getCodJg() {
        return this.codJg;
    }
    
    public void setCodJg(int codJg) {
        this.codJg = codJg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_adversario")
    public Adversarios getAdversarios() {
        return this.adversarios;
    }
    
    public void setAdversarios(Adversarios adversarios) {
        this.adversarios = adversarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_campeonato")
    public Campeonatos getCampeonatos() {
        return this.campeonatos;
    }
    
    public void setCampeonatos(Campeonatos campeonatos) {
        this.campeonatos = campeonatos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=13)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="gols_pro")
    public Integer getGolsPro() {
        return this.golsPro;
    }
    
    public void setGolsPro(Integer golsPro) {
        this.golsPro = golsPro;
    }

    
    @Column(name="gols_adv")
    public Integer getGolsAdv() {
        return this.golsAdv;
    }
    
    public void setGolsAdv(Integer golsAdv) {
        this.golsAdv = golsAdv;
    }

    
    @Column(name="local_jg", nullable=false)
    public String getLocalJg() {
        return this.localJg;
    }
    
    public void setLocalJg(String localJg) {
        this.localJg = localJg;
    }

    
    @Column(name="conteudo")
    public String getConteudo() {
        return this.conteudo;
    }
    
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    
    @Column(name="cod_comentario")
    public Integer getCodComentario() {
        return this.codComentario;
    }
    
    public void setCodComentario(Integer codComentario) {
        this.codComentario = codComentario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jogos")
    public Set getGolsAdvs() {
        return this.golsAdvs;
    }
    
    public void setGolsAdvs(Set golsAdvs) {
        this.golsAdvs = golsAdvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jogos")
    public Set getGolses() {
        return this.golses;
    }
    
    public void setGolses(Set golses) {
        this.golses = golses;
    }




}


