package br.com.gaiatosfc.model;
// Generated 22/04/2016 14:13:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Noticias generated by hbm2java
 */
@Entity
@Table(name="noticias"
    ,schema="public"
)
public class Noticias  implements java.io.Serializable {


     private int codN;
     private String titulo;
     private String foto;
     private String conteudo;
     private Integer codComentario;

    public Noticias() {
    }

	
    public Noticias(int codN, String titulo) {
        this.codN = codN;
        this.titulo = titulo;
    }
    public Noticias(int codN, String titulo, String foto, String conteudo, Integer codComentario) {
       this.codN = codN;
       this.titulo = titulo;
       this.foto = foto;
       this.conteudo = conteudo;
       this.codComentario = codComentario;
    }
   
     @Id 

    
    @Column(name="cod_n", unique=true, nullable=false)
    public int getCodN() {
        return this.codN;
    }
    
    public void setCodN(int codN) {
        this.codN = codN;
    }

    
    @Column(name="titulo", nullable=false, length=150)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="foto")
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    
    @Column(name="conteudo")
    public String getConteudo() {
        return this.conteudo;
    }
    
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    
    @Column(name="cod_comentario")
    public Integer getCodComentario() {
        return this.codComentario;
    }
    
    public void setCodComentario(Integer codComentario) {
        this.codComentario = codComentario;
    }




}


